In [12]:
import pandas as pd

# TODO: Set weight1, weight2, and bias
weight1 = 1.0
weight2 = 1.0
bias = -2.0


# DON'T CHANGE ANYTHING BELOW
# Inputs and outputs
test_inputs = [(0, 0), (0, 1), (1, 0), (1, 1)]
correct_outputs = [False, False, False, True]
outputs = []

# Generate and check output
for test_input, correct_output in zip(test_inputs, correct_outputs):
    linear_combination = weight1 * test_input[0] + weight2 * test_input[1] + bias
    output = int(linear_combination >= 0)
    is_correct_string = 'Yes' if output == correct_output else 'No'
    outputs.append([test_input[0], test_input[1], linear_combination, output, is_correct_string])

# Print output
num_wrong = len([output[4] for output in outputs if output[4] == 'No'])
output_frame = pd.DataFrame(outputs, columns=['Input 1', '  Input 2', '  Linear Combination', '  Activation Output', '  Is Correct'])
if not num_wrong:
    print('Nice!  You got it all correct.\n')
else:
    print('You got {} wrong.  Keep trying!\n'.format(num_wrong))
print(output_frame.to_string(index=False))

Nice!  You got it all correct.

Input 1    Input 2    Linear Combination    Activation Output   Is Correct
      0          0                  -2.0                    0          Yes
      0          1                  -1.0                    0          Yes
      1          0                  -1.0                    0          Yes
      1          1                   0.0                    1          Yes


In [27]:
import pandas as pd

# TODO: Set weight1, weight2, and bias
weight1 = 0.0
weight2 = -1.0
bias = 0.0


# DON'T CHANGE ANYTHING BELOW
# Inputs and outputs
test_inputs = [(0, 0), (0, 1), (1, 0), (1, 1)]
correct_outputs = [True, False, True, False]
outputs = []

# Generate and check output
for test_input, correct_output in zip(test_inputs, correct_outputs):
    linear_combination = weight1 * test_input[0] + weight2 * test_input[1] + bias
    output = int(linear_combination >= 0)
    is_correct_string = 'Yes' if output == correct_output else 'No'
    outputs.append([test_input[0], test_input[1], linear_combination, output, is_correct_string])

# Print output
num_wrong = len([output[4] for output in outputs if output[4] == 'No'])
output_frame = pd.DataFrame(outputs, columns=['Input 1', '  Input 2', '  Linear Combination', '  Activation Output', '  Is Correct'])
if not num_wrong:
    print('Nice!  You got it all correct.\n')
else:
    print('You got {} wrong.  Keep trying!\n'.format(num_wrong))
print(output_frame.to_string(index=False))

Nice!  You got it all correct.

Input 1    Input 2    Linear Combination    Activation Output   Is Correct
      0          0                   0.0                    1          Yes
      0          1                  -1.0                    0          Yes
      1          0                   0.0                    1          Yes
      1          1                  -1.0                    0          Yes


In [25]:
import numpy as np
# Setting the random seed, feel free to change it and see different solutions.
np.random.seed(42)

def stepFunction(t):
    if t >= 0:
        return 1
    return 0

def prediction(X, W, b):
    return stepFunction((np.matmul(X,W)+b)[0])

# TODO: Fill in the code below to implement the perceptron trick.
# The function should receive as inputs the data X, the labels y,
# the weights W (as an array), and the bias b,
# update the weights and bias W, b, according to the perceptron algorithm,
# and return W and b.
def perceptronStep(X, y, W, b, learn_rate = 0.01):
    #print(X)
    #print(y)
    for i in range(len(X)):
        y_pred = prediction(X[i], W, b)
        if y[i] - y_pred == 1:
                W[0] += X[i][0]*learn_rate
                W[1] += X[i][1]*learn_rate
                b += learn_rate
        elif y[i] - y_pred == -1:
                W[0] -= X[i][0]*learn_rate
                W[1] -= X[i][1]*learn_rate
                b -= learn_rate
    return W, b
    
# This function runs the perceptron algorithm repeatedly on the dataset,
# and returns a few of the boundary lines obtained in the iterations,
# for plotting purposes.
# Feel free to play with the learning rate and the num_epochs,
# and see your results plotted below.
def trainPerceptronAlgorithm(X, y, learn_rate = 0.01, num_epochs = 25):
    x_min, x_max = min(X.T[0]), max(X.T[0])
    y_min, y_max = min(X.T[1]), max(X.T[1])
    W = np.array(np.random.rand(2,1))
    b = np.random.rand(1)[0] + x_max
    # These are the solution lines that get plotted below.
    boundary_lines = []
    for i in range(num_epochs):
        # In each epoch, we apply the perceptron step.
        W, b = perceptronStep(X, y, W, b, learn_rate)
        boundary_lines.append((-W[0]/W[1], -b/W[1]))
    return boundary_lines

import pandas as pd

df = pd.read_csv('perceptron-data.csv', sep=',',header=None)
boundaries = trainPerceptronAlgorithm(np.array(df.loc[:,0:1]), np.array(df.loc[:,2]))
boundaries

[(array([-0.05239463]), array([-2.04919443])),
 (array([ 1.23772563]), array([-2.90815949])),
 (array([-39.47663703]), array([ 23.57864461])),
 (array([-13.13237331]), array([ 7.06473087])),
 (array([-9.11612538]), array([ 4.57527519])),
 (array([-7.79056954]), array([ 3.96940892])),
 (array([-6.7750263]), array([ 3.50523881])),
 (array([-5.97212608]), array([ 3.13826056])),
 (array([-5.32141098]), array([ 2.84084093])),
 (array([-4.78335796]), array([ 2.59491529])),
 (array([-4.33103935]), array([ 2.38817591])),
 (array([-4.09146109]), array([ 2.3928177])),
 (array([-3.80251597]), array([ 2.25914697])),
 (array([-3.54414571]), array([ 2.13962066])),
 (array([-3.31174122]), array([ 2.03210655])),
 (array([-3.10157551]), array([ 1.93488045])),
 (array([-2.91060228]), array([ 1.84653311])),
 (array([-2.73630733]), array([ 1.76590142])),
 (array([-2.57659722]), array([ 1.69201691])),
 (array([-2.4297148]), array([ 1.6240667])),
 (array([-2.29417429]), array([ 1.56136344])),
 (array([-2.16

In [39]:
import numpy as np

# Write a function that takes as input a list of numbers, and returns
# the list of values given by the softmax function.
def softmax(L):
    softmap = lambda t: np.exp(t) / np.exp(L).sum()
    return np.array([softmap(l) for l in L])

out = softmax([5, 6, 7])
out

array([ 0.09003057,  0.24472847,  0.66524096])

In [40]:
np.exp([5, 6, 7]).sum()

1648.4751110237703

In [41]:
np.exp(5)

148.4131591025766

In [43]:
# Solution from the course:

import numpy as np

def softmax(L):
    expL = np.exp(L)
    sumExpL = sum(expL)
    result = []
    for i in expL:
        result.append(i*1.0/sumExpL)
    return result
    
    # Note: The function np.divide can also be used here, as follows:
    # def softmax(L):
    #     expL = np.exp(L)
    #     return np.divide (expL, expL.sum())

In [53]:
import numpy as np

# Write a function that takes as input two lists Y, P,
# and returns the float corresponding to their cross-entropy.
def cross_entropy(Y, P):
    P1 = np.subtract(1, P)
    Y1 = np.subtract(1, Y)
    ln_P = np.log(P)
    ln_P1 = np.log(P1)
    return -(np.sum(Y*ln_P + Y1*ln_P1))

Y=[1,0,1,1]
P=[0.4,0.6,0.1,0.5]
print(cross_entropy(Y, P))

4.8283137373
