In [2]:
import numpy as np


s = np.array(5)
s.shape

()

In [4]:
x = s + 3
x

8

In [8]:
v = np.array([1,2,3])
v.shape
x = v[1]
x

2

In [9]:
v[1:]

array([2, 3])

In [10]:
m = np.array([[1,2,3], [4,5,6], [7,8,9]])
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
m.shape

(3, 3)

In [12]:
# Tensor
t = np.array([[[[1],[2]],[[3],[4]],[[5],[6]]],[[[7],[8]],\
    [[9],[10]],[[11],[12]]],[[[13],[14]],[[15],[16]],[[17],[17]]]])

In [13]:
t.shape

(3, 3, 2, 1)

In [15]:
t[2][1][1][0]

16

In [17]:
# Changing shapes
v = np.array([1,2,3,4])
v

array([1, 2, 3, 4])

In [21]:
# To 1x4 Matrix
x = v.reshape(1,4)
x

array([[1, 2, 3, 4]])

In [22]:
v.shape

(4,)

In [23]:
x.shape

(1, 4)

In [25]:
x = v[None, :]
x

array([[1, 2, 3, 4]])